title: "Bayesian analysis of respondent-driven sampling with outcome
uncertainty"
execute:
  execute_notebooks: "off"
bibtex_bibfiles:
    - biblio.bib
sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
